java_doc:
	javadoc -private -d javadocs -sourcepath  /usr/gleeson/our_subs/java/Projects/AmLibTech.com \
		com.amlibtech.io \
		com.amlibtech.util \
		com.amlibtech.web \
		com.amlibtech.web.common_list \
		com.amlibtech.web.data \
		com.amlibtech.web.database \
		com.amlibtech.web.navigation \
		com.amlibtech.web.servlet_exceptions \
		com.amlibtech.web.util \
		com.amlibtech.database \
		com.amlibtech.data_fields \
		com.amlibtech.html_Tags \
		com.amlibtech.login \
		com.amlibtech.login.data \
		com.amlibtech.login.sql_scripts \
		com.amlibtech.security_Management \
		com.amlibtech.security_Management.data \
		com.amlibtech.security_Management.data.list \
		com.amlibtech.site_Management \
		com.amlibtech.site_Management.data \
		com.amlibtech.web_Processes
