.SUFFIXES: .java .class
HOME=/usr/gleeson
MODE=4711
GROUP=gleeson
LPGROUP=lp_admin
LD_FLAGS=

.java.class:
	javac  $<


#------------------------------------------------------------------------------|
#	Copyright (c) 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993     |
#	Gleeson and Associates                                                 |
#	All Rights Reserved                                                    |
#                                                                              |
#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF                         |
#	Gleeson And Associates                                                 |
#	The copyright notice above does not evidence any                       |
#	actual or intended publication of such source code.                    |
#------------------------------------------------------------------------------|

All: HelloDan.class Palindrome.class

HelloDan.class: HelloDan.java

Palindrome.class: Palindrome.java

