/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JIsam */

#ifndef _Included_JIsam
#define _Included_JIsam
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JIsam
 * Method:    create
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_JIsam_create
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     JIsam
 * Method:    setup_new_file
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_JIsam_setup_1new_1file
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     JIsam
 * Method:    initialize_alloc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JIsam_initialize_1alloc
  (JNIEnv *, jobject);

/*
 * Class:     JIsam
 * Method:    insert
 * Signature: (ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_JIsam_insert
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     JIsam
 * Method:    next
 * Signature: (ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_JIsam_next
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     JIsam
 * Method:    prev
 * Signature: (ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_JIsam_prev
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     JIsam
 * Method:    fkl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JIsam_fkl
  (JNIEnv *, jobject, jint);

/*
 * Class:     JIsam
 * Method:    frl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JIsam_frl
  (JNIEnv *, jobject, jint);

/*
 * Class:     JIsam
 * Method:    lock
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JIsam_lock
  (JNIEnv *, jobject, jint);

/*
 * Class:     JIsam
 * Method:    unlock
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JIsam_unlock
  (JNIEnv *, jobject, jint);

/*
 * Class:     JIsam
 * Method:    wait_lock
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JIsam_wait_1lock
  (JNIEnv *, jobject, jint);

/*
 * Class:     JIsam
 * Method:    r_lock
 * Signature: (IJI)I
 */
JNIEXPORT jint JNICALL Java_JIsam_r_1lock
  (JNIEnv *, jobject, jint, jlong, jint);

/*
 * Class:     JIsam
 * Method:    r_unlock
 * Signature: (IJI)V
 */
JNIEXPORT void JNICALL Java_JIsam_r_1unlock
  (JNIEnv *, jobject, jint, jlong, jint);

/*
 * Class:     JIsam
 * Method:    print_lock_list
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JIsam_print_1lock_1list
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
