.SUFFIXES: .c .o
HOME=/usr/gleeson
MODE=4711
GROUP=gleeson

.c.o:
	$(CC) -c $< $(CFLAGS)



#------------------------------------------------------------------------------|
#       Copyright (c) 1985 thru 1991, 1992, 1993, 1994, 1995, 1996, 1997       |
#       Gleeson and Associates                                                 |
#       All Rights Reserved                                                    |
#                                                                              |
#       THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF                         |
#       Gleeson And Associates                                                 |
#       The copyright notice above does not evidence any                       |
#       actual or intended publication of such source code.                    |
#------------------------------------------------------------------------------|


milan: $(SYSTEM_MFG)



mips:
	make -f MakeMIPS


aix:
	make -f MakeRS6k

