#! /bin/sh
# get_cpu_code

#------------------------------------------------------------------------------|
#	Copyright (c) 1985 thru 1996, 1997, 1998, 1999, 2000, 2001, 2002       |
#	Gleeson and Associates                                                 |
#	All Rights Reserved                                                    |
#                                                                              |
#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF                         |
#	Gleeson And Associates                                                 |
#	The copyright notice above does not evidence any                       |
#	actual or intended publication of such source code.                    |
#------------------------------------------------------------------------------|

awk '
BEGIN {
	is_pentium=0
	is_amd=0
	have_family=0
}
{
	if ( $1 == "model" && $2 == "name" )
		if ($4 == "Pentium")
			is_pentium=1
		if (substr($4,1,3) == "AMD")
			is_amd=1
	if ( $1 == "cpu" && $2 == "family" ){
		have_family=1
		cpu_family=$4
	}
}
END{
	if ( is_pentium == 1 && have_family == 1)
		printf "i%d86\n", cpu_family
	if ( is_amd == 1 && have_family == 1)
		printf "i%d86\n", cpu_family
}
' </proc/cpuinfo
