.SUFFIXES: .c .o
HOME=/usr/gleeson
GROUP=gleeson
MODE=700

.c.o:
	$(CC) -c $< $(CFLAGS) 



#------------------------------------------------------------------------------|
#	Copyright (c) 1985 thru 1996, 1997, 1998, 1999, 2000, 2001, 2002       |
#	Gleeson and Associates                                                 |
#	All Rights Reserved                                                    |
#                                                                              |
#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF                         |
#	Gleeson And Associates                                                 |
#	The copyright notice above does not evidence any                       |
#	actual or intended publication of such source code.                    |
#------------------------------------------------------------------------------|



webtools: form2cgi

include form2cgi.M

